 CREATE TABLE IF NOT EXISTS `progress` (  
 
`siteid` TEXT NOT NULL,
`breakdown` TEXT NOT NULL,
`siteType` TEXT NOT NULL,
`siteName` TEXT NOT NULL,
`region` TEXT NOT NULL,
`subRegion` TEXT NOT NULL,
`configuration` TEXT NOT NULL,
`4gConfiguration` TEXT NOT NULL,
`PMC` TEXT NOT NULL,
`firstCutPR` TEXT NOT NULL,
`firstCutPRActual` DATE NOT NULL,
`firstCutPO` TEXT NOT NULL,
`firstCutPOActual` DATE NOT NULL,
`secondCutPR` TEXT NOT NULL,
`secondCutPRActual` DATE NOT NULL,
`secondCutPO` TEXT NOT NULL,
`secondCutPOActual` DATE NOT NULL,
`ownerType` TEXT NOT NULL,
`owner` TEXT NOT NULL,
`TSSRBaseline` DATE NOT NULL,
`TSSRPlan` DATE NOT NULL,
`TSSRActual` DATE NOT NULL,
`TXBaseline` DATE NOT NULL,
`TXPlan` DATE NOT NULL,
`TXActual` DATE NOT NULL,
`SABaseline` DATE NOT NULL,
`SAPlan` DATE NOT NULL,
`SAActual` DATE NOT NULL,
`CSIBaseline` DATE NOT NULL,
`CSIPlan` DATE NOT NULL,
`CSIActual` DATE NOT NULL,
`CMEBaseline` DATE NOT NULL,
`CMEPlan` DATE NOT NULL,
`CMEActual` DATE NOT NULL,
`TIBaseline` DATE NOT NULL,
`TIPlan` DATE NOT NULL,
`TIActual` DATE NOT NULL,
`IntBaseline` DATE NOT NULL,
`IntPlan` DATE NOT NULL,
`IntActual` DATE NOT NULL,
`SSVBaseline` DATE NOT NULL,
`SSVPlan` DATE NOT NULL,
`SSVActual` DATE NOT NULL,
`OAActualTechincal` DATE NOT NULL,
`OABaseline` DATE NOT NULL,
`OAPlan` DATE NOT NULL,
`OAActual` DATE NOT NULL,
`PACBaseline` DATE NOT NULL,
`PACPLan` DATE NOT NULL,
`PACActual` DATE NOT NULL,
`FACBaseline` DATE NOT NULL,
`FACPlan` DATE NOT NULL,
`FACActual` DATE NOT NULL,
`district` TEXT NOT NULL,
`state` TEXT NOT NULL,
`driver` TEXT NOT NULL,
`regionalCluster` TEXT NOT NULL,
`regionalClusterName` TEXT NOT NULL,
`salesFocusCluster` TEXT NOT NULL,
`IntG18Actual` DATE NOT NULL,
`IntU21Actual` DATE NOT NULL,
`IntL09Actual` DATE NOT NULL,
`IntL18Actual` DATE NOT NULL,
`IntL26Actual` DATE NOT NULL,
`OAG18Actual` DATE NOT NULL,
`OAL21Actual` DATE NOT NULL,
`OAL09Actual` DATE NOT NULL,
`OAL18Actual` DATE NOT NULL,
`OAL26Actual` DATE NOT NULL,



	 PRIMARY KEY (`siteid`)
 ) 